apiVersion: v1
kind: Secret
metadata:
  name: smsservices-secret
  namespace: nm-ivr-evolucion-dev
type: Opaque
data: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: smsservices-config
  namespace: nm-ivr-evolucion-dev
data:
  SERVER_PORT: "8080"
  SPRING_APPLICATION_NAME: "smsservices"
  LOGGING_LEVEL_CO_COM_CLARO: "trace"
  LOGGING_PATTERN_CONSOLE: "{\"applicationName\":\"${spring.application.name}\", \"methodName\":\"%M\", \"transactionId\":\"%X{X-B3-TraceId:-}\", \"level\": \"%p\", \"message\": \"%replace(%m%wEx{6}){'[\r\n]+', '\\n'}%nopex\", \"processingTime\":\"\", \"timestamp\": \"%d\", \"source\": \"%logger{63}:%L\"}%n"
  LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WS_CLIENT_MESSAGETRACING_SENT: "TRACE"
  LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WS_SERVER_MESSAGETRACING_SENT: "TRACE"
  LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WS_CLIENT_MESSAGETRACING_RECEIVED: "TRACE"
  LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WS_SERVER_MESSAGETRACING_RECEIVED: "TRACE"
---
apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: smsservices
    legado: SMS
    proyecto: IVR
    subproyecto: SMS
    tecnologia: SpringBoot-Maven
  name: smsservices
  namespace: nm-ivr-evolucion-dev
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: smsservices
    deploymentconfig: smsservices
  strategy:
    activeDeadlineSeconds: 21600
    resources:
      limits:
        cpu: 200m
        memory: 300Mi
      requests:
        cpu: 100m
        memory: 100Mi
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 120
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        app: smsservices
        deploymentconfig: smsservices
      name : smsservices
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: smsservices-config
            - secretRef:
                name: smsservices-secret
          image: docker-registry.default.svc:5000/nm-ivr-evolucion-dev/smsservices:latest
          imagePullPolicy: IfNotPresent
          name: smsservices
          ports:
            - name : service-port
              containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 200m
              memory: 300Mi
            requests:
              cpu: 10m
              memory: 10Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: smsservices
  name: smsservices
  namespace: nm-ivr-evolucion-dev
spec:
  ports:
    - name : service-port
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: smsservices
    deploymentconfig: smsservices
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Route
metadata:
  labels:
    app: smsservices
  name: smsservices
  namespace: nm-ivr-evolucion-dev
spec:
  port:
    targetPort: service-port
  to:
    kind: Service
    name: smsservices
    weight: 100
  wildcardPolicy: None
